### ISSUE TITLE
queryHitPathways API is restricted to human

### ISSUE THREAD

**Issue by teheavy** [reactome/Release#1]
Hi,

I'm a developer who is trying to get Arabidopsis thaliana pathways from queryHitPathways API, but I'm not sure when will be this API open to other species. 

Thanks!

**Comment by fabregat** [comment]
Hi,

I recommend you to have a look at the developer guide (http://www.reactome.org/pages/documentation/developer-guide/) where you can find the RESTful API (http://www.reactome.org/pages/documentation/developer-guide/restful-service/) where the queryHitPathways is but also to Analysis Service (http://www.reactome.org/pages/documentation/developer-guide/analysis-service/) which API is http://www.reactome.org/AnalysisService/

If you use the analysis service, please be sure that you don't use the projection methods so you will get the results in your species of interest. Finally, and taking into account your requirements, I also recommend you to use protein accessions rather than gene names.

Thank you for your interest in Reactome!

**Comment by teheavy** [comment]
Hi fabregat,

Thanks for the help! I've tried to use the analysis service to get query hits, however, it seems all the ones I tried on Arabidopsis does not give me any result.

AGI: AT1G68020
Uniprot: Q94AH8
http://www.reactome.org:80/AnalysisService/identifier/Q94AH8?pageSize=20&page=1&sortBy=ENTITIES_PVALUE&order=ASC&resource=UNIPROT

AGI: AT4G18780
Uniprot: Q8LPK5

and a different plant species
Uniprot: Q0JKD0

But it works with Plant Reactome (although there's something wrong with search function) 
http://plantreactome.gramene.org/content/query?q=AT1G68020&species=Arabidopsis+thaliana&cluster=true

So I'm thinking that maybe Reactome database is not connected to Plant Reactome, is that right?

Thanks,
Fred

**Comment by fabregat** [comment]
You're right.

They are two different projects (even though they share the code).

You also have an AnalysisService in Plant Reactome

http://plantreactome.gramene.org/AnalysisService/

Please note that you can use the "identifiers" method to submit all your protein identifiers and then get the list of most significant pathways there.

Thank you for your interest in Reactome.

Best regards,

**Comment by preecej** [comment]
Fred,

Plant Reactome developer here. It is true that some API functions (like queryHitPathways) are still restricted to H.sapiens results, even in the Plant Reactome. I'm working on removing that restriction now. I'll keep you updated.

**Comment by teheavy** [comment]
Great! Thank you guys! I used Analysis Service from Plant Reactome and got the solution I wanted!

**Comment by teheavy** [comment]
Oh, sorry, one more question. Since I'm currently using analysis service to get query result and export pathway using the BioPax level 3 format, I'm wondering if the service can also return an SBGN diagram?

Thanks!
Fred

**Comment by preecej** [comment]
You could download any pathway in SBML...

http://plantreactome.gramene.org/ReactomeRESTfulAPI/RESTfulWS/sbmlExporter/6788019

...and then convert to SBGN using an external tool.

**Comment by teheavy** [comment]
Thanks! I found tools that can convert files from BioPAX to SBGN.
